version: "1.1"
services:
 db:
  image: postgres:latest
  ports:
   - 5430:5432
  environment:
   POSTGRES_DB: postgres
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  volumes:
   - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql