version: "1.2"
services:
  app:
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:latest
    ports:
      - 5430:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always